version: "3"
services:
  url:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mydb:3306/short_link?allowPublicKeyRetrieval=true
    depends_on:
      mydb:
          condition: service_healthy
  mydb:
    image: mysql:8.4.0
    restart: "always"
    environment:
      MYSQL_DATABASE: short_link
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: